[package]
name = "evm-assembler"
version = "0.1.0"
authors = ["Ainevsia <ainevsia@pm.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
